/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal_tbd.vista;

import com.mycompany.proyectofinal_tbd.dao.ObraDAO;
import com.mycompany.proyectofinal_tbd.dao.ObraDAOImpl;
import com.mycompany.proyectofinal_tbd.dao.ProduccionDAO;
import com.mycompany.proyectofinal_tbd.dao.ProduccionDAOImpl;
import com.mycompany.proyectofinal_tbd.modelo.Obra;
import com.mycompany.proyectofinal_tbd.modelo.Produccion;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;


/**
 *
 * @author banue
 */
public class ProduccionVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProduccionVista.class.getName());

    private ProduccionDAO produccionDAO = new ProduccionDAOImpl();
    private ObraDAO obraDAO = new ObraDAOImpl();
    
    private DefaultTableModel modeloTabla;
    private JTable tablaProducciones;

    private JTextField txtLugar, txtFecha;
    private JComboBox<Obra> comboObra;
    private JRadioButton rbActiva, rbInactiva;
    private ButtonGroup grupoEstado;

    private JButton btnGuardar, btnEditar, btnEliminar, btnLimpiar;
    private Produccion produccionSeleccionada = null;

    /**
     * Creates new form ProduccionVista
     */
    public ProduccionVista() {
        initComponents();
        configurarVentana();
        //cargarObrasEnCombo();
        cargarProducciones();
    }//public ProduccionVista

    private void configurarVentana() {
        setTitle("Gestión de Producciones");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(950, 700);
        setLocationRelativeTo(null);

        getContentPane().setBackground(new Color(255, 240, 248)); 

        estiloBoton(btnGuardar, new Font("Segoe UI", Font.BOLD, 16), new Color(180, 240, 200));
        estiloBoton(btnEditar, new Font("Segoe UI", Font.BOLD, 16), new Color(200, 130, 150));
        estiloBoton(btnEliminar, new Font("Segoe UI", Font.BOLD, 16), new Color(255, 180, 180));
        estiloBoton(btnLimpiar, new Font("Segoe UI", Font.BOLD, 16), new Color(230, 230, 250));

        tablaProducciones.getTableHeader().setBackground(new Color(230, 180, 200));
        tablaProducciones.getTableHeader().setForeground(Color.WHITE);
        tablaProducciones.setSelectionBackground(new Color(200, 130, 150));
    }//configurarVentana
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estiloBoton(JButton btn, Font fuente, Color colorFondo) {
        btn.setFont(fuente);
        btn.setPreferredSize(new Dimension(120, 32));
        btn.setFocusable(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setBackground(colorFondo);
        btn.setForeground(Color.WHITE);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
    }//EstiloBoton

    private void guardarProduccion() {
        if (!validarCampos()) return;

        Produccion p = new Produccion();
        p.setIdProduccion(produccionSeleccionada != null ? produccionSeleccionada.getIdProduccion() : null);
        p.setIdObra(((Obra) comboObra.getSelectedItem()).getIdObra());
        //p.setLugar(txtLugar.getText().trim());
        //p.setFechaEstreno(txtFecha.getText().trim());
        //p.setEstado(rbActiva.isSelected() ? "Activa" : "Inactiva");

        if (produccionSeleccionada == null) {
            // Alta
            produccionDAO.insertar(p, () -> {
                JOptionPane.showMessageDialog(this, "Producción guardada", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                cargarProducciones();
            }, () -> {
                JOptionPane.showMessageDialog(this, "Error al guardar", "Error", JOptionPane.ERROR_MESSAGE);
            });
        } else {
            // Cambio
            produccionDAO.actualizar(p, () -> {
                JOptionPane.showMessageDialog(this, "Producción actualizada", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                cargarProducciones();
            }, () -> {
                JOptionPane.showMessageDialog(this, "Error al actualizar", "Error", JOptionPane.ERROR_MESSAGE);
            });
        }//else
    }//guardarProduccion
    
    private void editarObra() {
        if (produccionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una producción", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }//if
        
        guardarProduccion();
    }//EditarObra

    private void eliminarProduccion() {
        if (produccionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una producción", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }//if

        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Eliminar la producción de '" + ((Obra) comboObra.getSelectedItem()).getTitulo() + "'?\n(Se eliminarán sus datos)",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            produccionDAO.eliminar(produccionSeleccionada.getIdProduccion(), () -> {
                JOptionPane.showMessageDialog(this, "Producción eliminada", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                cargarProducciones();
            }, () -> {
                JOptionPane.showMessageDialog(this, "Error al eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            });
        }//if
    }//eliminarProcuccion

    
    private boolean validarCampos() {
        // Validar obra seleccionada
        if (comboObra.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                "La obra es obligatoria.\nPor favor, selecciona una obra.",
                "Campo obligatorio",
                JOptionPane.WARNING_MESSAGE);
            comboObra.requestFocus();
            return false;
        }//if

        //validar lugar
        String lugar = txtLugar.getText().trim();
        if (lugar.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "El lugar es obligatorio.\nPor favor, ingresa el lugar de la producción.",
                "Campo obligatorio",
                JOptionPane.WARNING_MESSAGE);
            txtLugar.requestFocus();
            return false;
        }//if
        
        if (!lugar.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s\\-\\.,]+")) {
            JOptionPane.showMessageDialog(this,
                "El lugar solo puede contener letras, números, espacios, guiones y puntos.\nPor ejemplo: \"Teatro Principal\"",
                "Formato inválido",
                JOptionPane.ERROR_MESSAGE);
            txtLugar.selectAll();
            txtLugar.requestFocus();
            return false;
        }//if

        // Validar fecha (formato DD/MM/YYYY)
        String fechaStr = txtFecha.getText().trim();
        if (fechaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "La fecha de estreno es obligatoria.\nFormato: DD/MM/YYYY",
                "Campo obligatorio",
                JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocus();
            return false;
        }//if
        
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate.parse(fechaStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this,
                "Formato de fecha inválido.\nUsa DD/MM/YYYY. Ejemplo: 15/05/2025",
                "Formato de fecha",
                JOptionPane.ERROR_MESSAGE);
            txtFecha.selectAll();
            txtFecha.requestFocus();
            return false;
        }//catch

        return true;
    }//validar
    
        private void cargarProduccionSeleccionada(int fila) {
        Long idProduccion = (Long) modeloTabla.getValueAt(fila, 0);
        produccionSeleccionada = produccionDAO.buscarPorId(idProduccion);

        if (produccionSeleccionada != null) {
            // Seleccionar la obra en el combo
            List<Obra> obras = obraDAO.listarTodas();
            for (Obra obra : obras) {
                if (obra.getIdObra().equals(produccionSeleccionada.getIdObra())) {
                    comboObra.setSelectedItem(obra);
                    break;
                }//if
            }//fro
            
           // txtLugar.setText(produccionSeleccionada.getLugar());
            //txtFecha.setText(produccionSeleccionada.getFechaEstreno());
            if ("Activa".equals(produccionSeleccionada.getEstado())) {
                rbActiva.setSelected(true);
            } else {
                rbInactiva.setSelected(true);
            }//else
        }//if afuera
    }//CargarPorduccion

    private void limpiarFormulario() {
        comboObra.setSelectedIndex(-1);
        txtLugar.setText("");
        txtFecha.setText("");
        rbActiva.setSelected(true);
        produccionSeleccionada = null;
    }//limpiarFormulario

    private void cargarProducciones() {
        modeloTabla.setRowCount(0);
        List<Produccion> producciones = produccionDAO.listarTodas();
        for (Produccion p : producciones) {
            Obra obra = obraDAO.buscarPorId(p.getIdObra());
            String nombreObra = (obra != null) ? obra.getTitulo() : "Obra no encontrada";
            modeloTabla.addRow(new Object[]{
                p.getIdProduccion(),
                nombreObra,
                //p.getFechaEstreno(),
                //p.getLugar(),
                //p.getEstado()
            });
        }//for
    }//cargarProducciones

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        guardarProduccion();
    }//guardar

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {
        if (produccionSeleccionada != null) {
            guardarProduccion();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una producción para editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }//else
    }//editar

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        eliminarProduccion();
    }//eliimnar

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        limpiarFormulario();
    }//limpiar
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }//if
            }//for
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }//Catch
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new ProduccionVista().setVisible(true));
    }//void main
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
 
}//public class

